# Generated by Django 5.2.8 on 2025-11-21 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=17, unique=True, verbose_name='VIN')),
                ('model_name', models.CharField(max_length=100, verbose_name='Модель')),
                ('trim_level', models.CharField(max_length=100, verbose_name='Комплектация')),
                ('color_exterior', models.CharField(max_length=50, verbose_name='Цвет кузова')),
                ('year_manufacture', models.IntegerField(verbose_name='Год выпуска')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')),
                ('status', models.CharField(choices=[('in_stock', '✅ В наличии'), ('in_transit', '🚚 В пути'), ('reserved', '🔒 Забронирован'), ('sold', '💰 Продан')], default='in_stock', max_length=20)),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('passport_series', models.CharField(blank=True, max_length=4, verbose_name='Серия паспорта')),
                ('passport_number', models.CharField(blank=True, max_length=6, verbose_name='Номер паспорта')),
                ('source', models.CharField(choices=[('website', '🌐 Сайт'), ('phone', '📞 Телефон'), ('showroom', '🏢 Шоу-рум'), ('recommendation', '👥 Рекомендация')], max_length=100, verbose_name='Источник')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', '🆕 Новая'), ('in_progress', '🔄 В работе'), ('presentation', '📊 Презентация'), ('test_drive', '🚗 Тест-драйв'), ('contract', '📝 Оформление'), ('success', '✅ Успех'), ('failed', '❌ Провал')], default='new', max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('assigned_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
