# Generated by Django 5.2.8 on 2025-11-21 17:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['-warehouse_arrival_date'], 'verbose_name': 'Автомобиль', 'verbose_name_plural': 'Автомобили'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-created_at'], 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-created_date'], 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AddField(
            model_name='car',
            name='color_interior',
            field=models.CharField(blank=True, max_length=50, verbose_name='Цвет салона'),
        ),
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='car',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='cars/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='car',
            name='warehouse_arrival_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата поступления'),
        ),
        migrations.AddField(
            model_name='client',
            name='passport_issued_by',
            field=models.TextField(blank=True, verbose_name='Кем выдан'),
        ),
        migrations.AddField(
            model_name='client',
            name='registration_address',
            field=models.TextField(blank=True, verbose_name='Адрес регистрации'),
        ),
        migrations.AddField(
            model_name='client',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='initial_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='lead',
            name='priority',
            field=models.IntegerField(choices=[(1, '🔴 Высокий'), (2, '🟡 Средний'), (3, '🟢 Низкий')], default=2, verbose_name='Приоритет'),
        ),
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.CharField(default=1, max_length=100, verbose_name='Источник заявки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=50, unique=True, verbose_name='Номер договора')),
                ('contract_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата заключения')),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Итоговая цена')),
                ('payment_type', models.CharField(choices=[('cash', '💵 Наличные'), ('loan', '🏦 Кредит'), ('installment', '📅 Рассрочка')], max_length=20, verbose_name='Тип оплаты')),
                ('signed', models.BooleanField(default=False, verbose_name='Подписан')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.car', verbose_name='Автомобиль')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.client', verbose_name='Клиент')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договоры',
                'ordering': ['-contract_date'],
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('call', '📞 Звонок'), ('email', '✉️ Email'), ('meeting', '👥 Встреча'), ('test_drive', '🚗 Тест-драйв'), ('note', '📝 Заметка')], max_length=20, verbose_name='Тип взаимодействия')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время')),
                ('result', models.TextField(verbose_name='Результат')),
                ('next_contact_date', models.DateTimeField(blank=True, null=True, verbose_name='Следующий контакт')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.client', verbose_name='Клиент')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': 'Взаимодействие',
                'verbose_name_plural': 'Взаимодействия',
                'ordering': ['-date_time'],
            },
        ),
    ]
